### ISSUE TITLE
Issues on Windows... looks to be path related

### ISSUE THREAD

**Issue by firecube** [resin-os/resin-device-toolbox#44]
Hi,

If I push a basic Mosquitto container on Windows I get the error...

rdt push failed. Error: Error while starting container mosquitto: Error: (HTTP code 500) server error - create \mnt\data\resin-data\mosquitto: volume name invalid: "\\mnt\\data\\resin-data\\mosquitto" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed

The same Dockerfile works on Linux and on Bash for Windows.

Also the rdt flash command doesn't work as it can't find the image.  I presume this is the same problem.

Thanks, Simon

**Comment by lekkas** [comment]
@firecube `rdt` has not been tested on the standard Windows cmd shell and the Windows environment in general is not thoroughly tested unfortunately. However, let us know on issues you hit on Bash for Windows which presumably is closer to the shell environment that `rdt` requires

**Comment by firecube** [comment]
Everything works for me on bash for Windows apart from the flash as currently access to removal media is not enabled.
