### ISSUE TITLE
add a timeout option for rdt scan.

### ISSUE THREAD

**Issue by shaunmulligan** [resin-os/resin-device-toolbox#49]
Often its good to have `rdt scan` for a minute or two while waiting for the device to come up on the local network. I would be great to have something like:

` rdt scan --timeout 1200` 

where timeout is in seconds.

**Comment by lekkas** [comment]
@hedss is this closed?

**Comment by hedss** [comment]
@lekkas Sorry yes, slipped through the cracks.
