### ISSUE TITLE
rdt push error on Windows 10

### ISSUE THREAD

**Issue by nmaas87** [resin-os/resin-device-toolbox#52]
I tried following:

git clone https://github.com/nmaas87/resin-openwrt-flask-app.git
cd resin-openwrt-flask-app
rdt push [IPofMyRPi3WithResinOS] –s . –n flask

* Building..
- Stopping and Removing any previous 'flask' container
- Building new 'flask' image
Step 1 : FROM nmaas87/rpi-openwrt:15.05.1_rpi
 ---> 9f459c83d25e
Step 2 : RUN opkg update &&     opkg install wget ca-certificates libffi libopenssl python-openssl python &&     cd /tmp &&     wget https://bootstrap.pypa.io/get-pip.py && python get-pip.py &&     pip install --no-cache-dir Flask &&     mkdir /app/ /app/templates
 ---> Running in 9c22128e8d95
Successfully installed Flask-0.11.1 Jinja2-2.8 MarkupSafe-0.23 Werkzeug-0.11.11 click-6.6 itsdangerous-0.24
 ---> 3bbc32c681b9
Removing intermediate container 9c22128e8d95
Step 3 : COPY app.py /app/
 ---> 2642ad2c9384
Removing intermediate container e935b5b654e6
Step 4 : COPY templates/index.html /app/templates/
 ---> 994bd3902702
Removing intermediate container 1480da258a85
Step 5 : EXPOSE 80
 ---> Running in c75a80019a49
 ---> 473ee0b52585
Removing intermediate container c75a80019a49
Step 6 : CMD python /app/app.py
 ---> Running in 013821d228c5
 ---> 0c7a5de44470
Removing intermediate container 013821d228c5
Successfully built 0c7a5de44470
- Creating 'flask' container

he does built the container successfully, however, after that, this happens:

- Starting 'flask' container
rdt push failed. Error: Error while starting container flask: Error: (HTTP code 500) server error - create \mnt\data\resin-data\flask: volume name invalid: "\\mnt\\data\\resin-data\\flask" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed
  Error: Error while starting container flask: Error: (HTTP code 500) server error - create \mnt\data\resin-data\flask: volume name invalid: "\\mnt\\data\\resin-data\\flask" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed

    at C:\Program Files\nodejs\node_modules\resin-device-toolbox\node_modules\resin-sync\build\docker-utils.js:298:15
    at tryCatcher (C:\Program Files\nodejs\node_modules\resin-device-toolbox\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\resin-device-toolbox\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Program Files\nodejs\node_modules\resin-device-toolbox\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\resin-device-toolbox\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Program Files\nodejs\node_modules\resin-device-toolbox\node_modules\bluebird\js\release\promise.js:687:18)
    at Async._drainQueue (C:\Program Files\nodejs\node_modules\resin-device-toolbox\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (C:\Program Files\nodejs\node_modules\resin-device-toolbox\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\resin-device-toolbox\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

On the resinOS Device, the container does not show up on docker ps, but on docker ps -a:
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS               NAMES
0b1142438ee7        flask               "python /app/app.py"   4 minutes ago       Created                                 flask
root@resin:~#

However, port 80 is not bound to it and it stopped working.
Starting the container via hand docker start 0b11 does work:

CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS               NAMES
0b1142438ee7        flask               "python /app/app.py"   6 minutes ago       Up 43 seconds       80/tcp              flask

however, even though it is running, I cannot reach my flask instance. So, something is wrong here - I can access my container on the RPi directly (curl 172.17.0.2) - but not from outside the RPi, so something like the routing has been gone wrong... And that is maybe we happens on push. Any idea? Pushing this container from Ubuntu works.

**Comment by nmaas87** [comment]
OK it seems like something with the path description between Windows and resinOS is wrong. On bash for Ubuntu it works.

**Comment by lekkas** [comment]
Hey @nmaas87 , thanks for reporting this. I've just sent a PR to add a dependency section for Windows in the README. `rdt` has not been tested on the standard Windows `cmd` shell, but it should work fine in Bash environments.

**Comment by nmaas87** [comment]
@lekkas Thanks for including this in the README, that should help other people getting started 👍

**Comment by lekkas** [comment]
Merged #53
