### ISSUE TITLE
git missing after install, WiFi not connecting

### ISSUE THREAD

**Issue by ElectroCamel** [resin-os/resin-device-toolbox#60]
* `rdt` version: 0.0.8
* Operating system and architecture: Arch Linux x64, installing on Raspberry Pi 3 (ARM)
* `rdt` output with `--verbose` flag enabled: Unsure, `sudo rdt flash resin.img --verbose` returned no extra output 

After installing, git isn't installed on the system. Also, it doesn't connect to WiFi, although the interface exists. Ethernet seems to be working fine, maybe the problem is that my SSID has spaces? Do I need to escape them while setting the SSID while running `rdt configure`?

rdt isn't available on the RasPi too.

It also looks like the filesystem is in read-only mode...

Netither make nor gcc are available, so I can't install git from zip.

**Comment by ElectroCamel** [comment]
I misunderstood the tutorial, I'm sorry. 

In case someone has the same problem: `git` and `rdt` are supposed to be run from your PC, not from the installation.

**Comment by lekkas** [comment]
@ElectroCamel no worries, let us know if you have any other issues
