### ISSUE TITLE
rdt ssh into /bin/bash instead of /bin/sh

### ISSUE THREAD

**Issue by lfarkas** [resin-os/resin-device-toolbox#64]
it'd be nice (and the documentation also said in https://resinos.io/docs/raspberry-pi2/gettingstarted/#poking-around-resinos that rdt ssh into /bin/bash but currently into /bin/sh (anyway it's working the same in resin.io too). or at least make it configurable.

**Comment by lekkas** [comment]
@lfarkas should be fixed in `resin-device-toolbox@0.0.9`
