### ISSUE TITLE
/host_run/dbus is not mounted into the container as it is in resin.io

### ISSUE THREAD

**Issue by shaunmulligan** [resin-os/resin-device-toolbox#67]
* `rdt` version: 0.8
* Operating system and architecture: OS X (10.11.5)

In resin.io the supervisor bind mounts the following:
```
		exports.getDataPath(dataPath) + ':/data'
		'/lib/modules:/lib/modules'
		'/lib/firmware:/lib/firmware'
		'/run/dbus:/host_run/dbus'
		'/run/dbus:/host/run/dbus'
		'/var/lib/connman:/host/var/lib/connman'
```
as see in this [line](https://github.com/resin-io/resin-supervisor/blob/17cf19dfb36e81ff14526d8508c815cf53c6514f/src/utils.coffee#L256)

In the resin sync module we only bind mount '/run/dbus:/host/run/dbus'  as seen [here](https://github.com/resin-io-modules/resin-sync/blob/master/lib/docker-utils.coffee#L65)

We should bind-mount `'/run/dbus:/host_run/dbus'` as well.

**Comment by lekkas** [comment]
This was a patch fix released in  `resin-sync@6.1.3`, so simply reinstalling `rdt` should fix this issue.
