### ISSUE TITLE
Tab completion during `rdt ssh` has unexpected behaviour

### ISSUE THREAD

**Issue by shaunmulligan** [resin-os/resin-device-toolbox#69]
* `rdt` version: 0.0.8
* Operating system and architecture: OSX 10.11.5

If you drop into the container using `rdt ssh` and try use TAB completion in the terminal, the terminal seems to handle the TAB as an actual TAB and just move the cursor rightwards along the terminal.

I would expect it to complete the command or path suggestions as regular bash does.

**Comment by lekkas** [comment]
Connects to #64 

@shaunmulligan this is a side effect from `/bin/sh`, should we default to `/bin/bash` if it's available?

**Comment by shaunmulligan** [comment]
yup, i think that would be good. is that what we do in the webterminal too?

**Comment by lekkas** [comment]
@shaunmulligan should be fixed in `resin-device-toolbox@0.0.9`
