### ISSUE TITLE
Implement rdt join command to promote a resinOS device to resin.io

### ISSUE THREAD

**Issue by josephroberts** [resin-os/resin-device-toolbox#72]
The command suggested for implementation is:
```
rdt join [deviceIp | hostname]
```
Should the optional [deviceIp | hostname] not be supplied, then the join command will search for all resinOS devices currently available and request that the user selects one (similarly to other rdt commands, such as ssh).

once a device is selected rdt will SSH into the device and run the `./resin-provisioner' binary, passing CLI input/output back to the user

More info : https://github.com/resin-io/hq/pull/451

**Comment by lekkas** [comment]
@shaunmulligan @josephroberts have we decided on a name for this command in the recent product calls? `rdt join`, `rdt promote` and `rdt realm` have been suggested in the past.

**Comment by josephroberts** [comment]
@lekkas not that I am aware of, my vote would be for `rdt promote`

**Comment by lekkas** [comment]
Thank you @josephroberts , yeah it looks like it's still tbd, I think it's fine not to block on this and use the `rdt join` placeholder for now, pinging @alisondavis17 and @alexandrosm as well ^

**Comment by alexandrosm** [comment]
the latest thing we ended up with was "rdt promote", let's go with that for
now.

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by josephroberts** [comment]
missed of the `interactive` command that has been added in the latest version of `resin-provisioner`
